### PR TITLE
remove vep and unbind logical port event summary in event summary

### PR DESCRIPTION
**Pull request by wesleywesley**
In 4 usp port mode (p2p only, p2p+nt ep, p2p+mgt ep, and nt only),
the previous 3 mode report port event by usp pff in csr, while for
nt only mode, the port event is report by vep pff in csr.

this patch fix:
1. PFF CSR region should be 255 number instead of 48
2. use logical port event bitmap and port cnt register, which
correctly demonstrate the binded logical port and its number.
because, unbinded logical port also have effect instance in pff csr,
but it is not a source of port event
3. remove vep (p2p+nt ep and p2p+mgt ep) port event summary from
event summary

### CODE REVIEW

**Comment by wesleywesley** [comment]
@lsgunth 
Thx for comments.

- switchtec-specific capability which only available for P2P bridge functions(consider it as a logical port: USP and DSP) that already bind with a physical port and nt ep(usp contains only one nt ep), but reserved for other functions
switchtec-specific capability includes:
1. indirect gas access windows
2. nt crosslink reset register
3. port event (events that happen in a physical port)
- the maximum port(physical) number is 48
- the PFF CSR region in the gas contains configuration data for each p2p bridge and all vep.
the maximum supported pcie function number is 255
- there is a definition issue in dev spec, the range of usp/dsp/vep instance id should be 0-254, instead of 0-48

therefore, unbind P2P function and mgt ep(usp contains one p2p and on mgt ep)/nt ep (usp contains one p2p and one nt ep) should not occupied one of the 48 slots of port event summary.

**Comment by lsgunth** [comment]
The first two commits look fine. The third commit still looks completely broken and there still appears to be no understandable justification.

**Comment by wesleywesley** [comment]
@lsgunth 
thx for comments.

previous implementation of routine "ioctl_event_summary" based on following input:
1. pcie function number supported by pff csr region is 48
2. pcie function instance id range from 0 to 48
3. vep (usp+mgt ep/usp+nt ep) belongs to source of port event
4. unbind logical port same as already bind logical port, it is also one of the sources of port event

but the reality is:
1. pcie function number supported by pff csr region is 255
2. pcie function instance id range from 0 to 254
3. neither vep (usp+mgt ep/usp+nt ep) nor unbind logical port is source of port event, except for bound logical port and nt only vep 

so the previous implementation: take all of the so called valid (judge by vendor id in pff csr) "port event summary register"  into target array "port [48]" is not correct
because 
1. this array will includes unnecessary vep (usp+mgt ep/usp+nt ep)'s "port event summary register's value", but actually, this register is a reserved one for them
2.  same case for unbound logical port

suppose a situation: the previous 48 slot in pff csr are all unbound logical port and vep function, while all the bound logical port and nt ep only function located after them. in this case, previous implementation will get the false port event summary.

**Comment by lsgunth** [comment]
I still see no good reason to hide the "unnecessary" summary registers from userspace.

Moreover you are still breaking the indexing and pff_to_port and port_to_pff will no longer work. It's also causing a change in behaviour to how userspace sees things and indexes pffs and no justification that it will be forward and backwards compatible and I suspect it wont be. So NAK.

You can merge the first patch at least but the last one is broken.

**Comment by wesleywesley** [comment]
@lsgunth 
thx for comments.

1. pff_to_port/port_to_pff still work
port_to_pff have no impact by this patch
for pff_to_port, this function also works
the only one difference is, the index of "pff [48]" (member of struct switchtec_ioctl_event_summary ) no longer play the role of "instance id".
the struct switchtec_ioctl_event_summary have some change:
from __u32 pff[48]; 
to struct { 
		__u32 port; 
		__u32 inst; 
	} pff[48]; 
besides the port event summary member, an instance id member added.
so call pff_to_port, the pff.inst is the correct parameter, instead of the index number

2. original design "pff[48]"  (member of struct switchtec_ioctl_event_summary )
is based on the fact: pff number also is 48, but actually it is 255
so how to accommodate all of the 255 pff event summary in 48 slots?

maybe a method: change the "pff[48]"  to "pff[255]"? 
yes, it maybe a worked method.
but
1. from the comments of the code, the "pff" member is event summary for 48 (phy)ports, not for all pff
******************************************************************
/** @brief Bitmap of events in each port function */
	unsigned pff[SWITCHTEC_MAX_PORTS];
 ******************************************************************
2. this method is just push the "check of valid event summary" after the "copy all pff event summary(from csr to this array)"
we have to check the instance id of each of the 255 member, remove the invalid ones (veps and unbind ports) afterwards.
this patch is put the validation check before copy.

3. last but not least:
user is confused by vep/unbind port generating port event.
actually, only port bind with physical port, it can be source of port event.
we have not seen this false case, it is because the reserved register (port event summary) in case of unbind port & vep (usp+mgt/usp+nt), its value is 0.
but if some day, the reserved register used for other usage, its value is not zero, then false alarm will appear.

**Comment by lsgunth** [comment]
1) pff_to_port() applies because it's used by userspace to translate from the index of the pff event summary to a port number. You cannot change this as it's part of the userspace API. More over you are changing the index to something that's pretty much impossible to figure out what it applies to.
2) The comment may be ambiguous but the name of the field is clearly "pff" not "port".
3) What you say makes no sense to me.

Changing the array size of the pff array in the ioctl from 48 to 255 sounds like it should be done. It just has to be done *very* carefully to preserve forwards and backwards compatibility.

**Comment by wesleywesley** [comment]
@lsgunth 
thx for comments.

1. pff_to_port() is not changed. it still works. 
only change is: index of "pff[48]" is no longer instance id. so a member "inst" for store the instance id is added.

2. copy all the 255 pff's event summary register(or reserved ones) is based on:
a. besides bind ports/nt ep only veps, unbind ports/veps could also be source of port event
b. reserved register(port event summary)'s value is always 0
but a is wrong, while b is just a assumption.
this patch is precisely avoid a and b. 

3. even change pff[48] to pff[255] for smallest code change and compatibility, we still have to remove the vep/unbind port when display, "they are not a source of port event", they have no "port event summary register", but "reserved space" at the same offset
just as what I described, the difference is only on: "copy then remove" or "remove then copy"

**Comment by lsgunth** [comment]
First: big NAK on the new patch. It breaks compatibility with userspace. That's not allowed. You cannot change the ioctl structures without being very careful that existing code that's currently using it does not break. That includes old versions of switchtec-user which are immutable.

1. No it does not still work. If I find I have an event in pff[5] and call pff_to_port(5) I get garbage. That's the current interface and you _have_ to maintain that because that's what existing code does.

2. I don't know how this applies.

3. I also don't know how this applies.

**Comment by wesleywesley** [comment]
#43 : switchtec: Fix false maximum supported PCIe function number issue
solving the same problem while maintain the backward compatibility, so close this one accordingly.

**Pull request closed without merging**
