### PR TITLE
Add NTB support for Backport 3.10 to 4.3

### PR DESCRIPTION
**Pull request by PaulSelles**
Added NTB support for 3.10 to 4.3.

### CODE REVIEW

**Comment by lsgunth** [comment]
How could this possibly work? The NTB APIs you are using are not in those kernel versions.

Also, it's better to cherry pick existing commits instead of making new ones.

Logan

**Comment by PaulSelles** [comment]
I see were I wrong. This pull request for intended to support CentOS7 and RHEL7 which are currently on 3.10. RH has backported a lot for modules into 3.10. These changes should go into a new branch targeting the OS.

Let me know how you feel is best to move forward with this.

**Comment by lsgunth** [comment]
Yes, a new branch would be fine if you need it. First, I'd try the 4.3 branch on such a kernel. If it doesn't work out of the box, start a new branch based on the 4.3 branch and fix whatever needs to be fixed.

Logan

**Comment by PaulSelles** [comment]
Sounds good. 

Closing request.

**Pull request closed without merging**
